m
Signed-off-by: Mattias Andrée <maandree@operamail.com>

diff --git a/src/sweetiebot b/src/sweetiebot
--- a/src/sweetiebot
+++ b/src/sweetiebot
@@ -38,11 +38,14 @@ echo 'Scanning...'
 
 find '/usr/lib/sweetie-bot' | grep -v '~$' | while read module; do
     . "$module"
+    if [ ! $? = 0 ]; then
+	echo -e '\e[31mHelp, assistence is required. I believe there is something wrong with me!\e[00m'
+    fi
 done
 
 for exit_value in ${PIPESTATUS[*]}; do
     if [ ! $exit_value = 0 ]; then
-	echo "Oops, an error has occurred."
+	echo 'Oops, an error has occurred.'
 	exit $exit_value
     fi
 done
